export const ORDER_CREATE_REQUIST = "ORDER_CREATE_REQUIST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_DETAILS_REQUIST = "ORDER_DETAILS_REQUIST"
export const ORDER_DETAILS_SUCCESS = "ORDERDETAILSE_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUIST = "ORDER_PAY_REQUIST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const ORDER_USER_REQUIST = "ORDER_USER_REQUIST"
export const ORDER_USER_SUCCESS = "ORDER_USER_SUCCESS"
export const ORDER_USER_FAIL = "ORDER_USER_FAIL"

export const ORDER_DELETE_REQUIST = "ORDER_DELETE_REQUIST"
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS"
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL"