export const PRODUCT_LIST_REQUIST = "PRODUCT_LIST_REQUIST" ;
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS" ;
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL" ;

export const PRODUCT_DETAILS_REQUIST = "PRODUCT_DETAILS_REQUIST" ;
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS" ;
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL" ;