export const CART_ADD_ITEM = "CART_ADD_ITEM" ;
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPIN_ADDRESS = "CART_SAVE_SHIPPIN_ADDRESS"

export const CART_SAVE_PAYEMENT_METHOD = 'CART_SAVE_PAYEMENT_METHOD'