export const ORDER_CREATE_REQUIST = "ORDER_CREATE_REQUIST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL"

export const ORDER_DETAILS_REQUIST = "ORDER_DETAILS_REQUIST"
export const ORDER_DETAILS_SUCCESS = "ORDERDETAILSE_SUCCESS"
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL"